# Generated by Django 3.2.15 on 2022-09-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterModel',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='share.usermodel')),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='share.collagemodel', verbose_name='collage')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='share.majormodel', verbose_name='major')),
            ],
            options={
                'abstract': False,
            },
            bases=('share.usermodel',),
        ),
    ]
