# Generated by Django 3.2.15 on 2022-09-16 17:07

import apps.share.validators.user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=11, validators=[apps.share.validators.user.PhoneValidator()], verbose_name='phone')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='master.mastermodel', verbose_name='User')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMobileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=11, validators=[apps.share.validators.user.PhoneValidator()], verbose_name='Mobile')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='master.mastermodel', verbose_name='User')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserEmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='master.mastermodel', verbose_name='User')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(verbose_name='Address')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='master.mastermodel', verbose_name='User')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
