# Generated by Django 3.2.15 on 2022-09-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_useraddressmodel_useremailmodel_usermobilemodel_userphonemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailmodel',
            name='master',
        ),
        migrations.RemoveField(
            model_name='usermobilemodel',
            name='master',
        ),
        migrations.RemoveField(
            model_name='userphonemodel',
            name='master',
        ),
        migrations.DeleteModel(
            name='UserAddressModel',
        ),
        migrations.DeleteModel(
            name='UserEmailModel',
        ),
        migrations.DeleteModel(
            name='UserMobileModel',
        ),
        migrations.DeleteModel(
            name='UserPhoneModel',
        ),
    ]
