# Generated by Django 3.2.15 on 2022-10-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20220916_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastermodel',
            options={'verbose_name': 'Master', 'verbose_name_plural': 'Masters'},
        ),
    ]
