UNIVERSITY = "ISFAHAN"

BACHELOR_DEGREE = "BACHELOR"
MASTER_DEGREE = "MASTER"
DOCTORATE_DEGREE = "DOCTORATE"
DEGREE_CHOICES = (
    (BACHELOR_DEGREE, 'BACHELOR'),
    (MASTER_DEGREE, 'MASTER'),
    (DOCTORATE_DEGREE, 'DOCTORATE'),
)

MALE = 'Male'
Female = 'Female'
SEX_TYPE_CHOICES = (
    (MALE, 'Male'),
    (Female, 'Female')
)

STUDENT_USER_TYPE = 'STUDENT'
MASTER_USER_TYPE = 'MASTER'

SATURDAY = 'SATURDAY'
SUNDAY = 'SUNDAY'
MONDAY = 'MONDAY'
TUESDAY = 'TUESDAY'
WEDNESDAY = 'WEDNESDAY'
THURSDAY = 'THURSDAY'
FRIDAY = 'FRIDAY'
CLASS_DATE_CHOICES = (
    (SATURDAY, 'SATURDAY'),
    (SUNDAY, 'SUNDAY'),
    (MONDAY, 'MONDAY'),
    (TUESDAY, 'TUESDAY'),
    (WEDNESDAY, 'WEDNESDAY'),
    (THURSDAY, 'THURSDAY'),
    (FRIDAY, 'FRIDAY'),
)

CLASS_TIME_1 = '08:00 - 10:00'
CLASS_TIME_2 = '10:00 - 12:00'
CLASS_TIME_3 = '12:00 - 14:00'
CLASS_TIME_4 = '14:00 - 16:00'
CLASS_TIME_5 = '16:00 - 18:00'
CLASS_TIME_CHOICES = (
    (CLASS_TIME_1, '08:00 - 10:00'),
    (CLASS_TIME_2, '10:00 - 12:00'),
    (CLASS_TIME_3, '12:00 - 14:00'),
    (CLASS_TIME_4, '14:00 - 16:00'),
    (CLASS_TIME_5, '16:00 - 18:00'),
)
