UNIVERSITY = "ISFAHAN"

BACHELOR_DEGREE = "BACHELOR"
MASTER_DEGREE = "MASTER"
DOCTORATE_DEGREE = "DOCTORATE"
DEGREE_CHOICES = (
    (BACHELOR_DEGREE, 'BACHELOR'),
    (MASTER_DEGREE, 'MASTER'),
    (DOCTORATE_DEGREE, 'DOCTORATE'),
)

MALE = 'Male'
Female = 'Female'
SEX_TYPE_CHOICES = (
    (MALE, 'Male'),
    (Female, 'Female')
)
