UNIVERSITY = "ISFAHAN"

BACHELOR_DEGREE = "BACHELOR"
MASTER_DEGREE = "MASTER"
DOCTORATE_DEGREE = "DOCTORATE"
DEGREE_CHOICES = (
    (BACHELOR_DEGREE, 'کارشناسی'),
    (MASTER_DEGREE, 'ارشد'),
    (DOCTORATE_DEGREE, 'دکترا'),
)
