# Generated by Django 3.2.15 on 2022-09-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.CharField(choices=[('Male', 'آقا'), ('Female', 'خانم')], default='Male', max_length=6, verbose_name='جنسیت'),
        ),
    ]
