# Generated by Django 3.2.15 on 2022-09-09 18:37

import apps.share.validators.course
import apps.share.validators.user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20220909_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collagemodel',
            options={'verbose_name': 'collage', 'verbose_name_plural': 'collages'},
        ),
        migrations.AlterModelOptions(
            name='majormodel',
            options={'verbose_name': 'major', 'verbose_name_plural': 'majors'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='collagemodel',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Collage name'),
        ),
        migrations.AlterField(
            model_name='majormodel',
            name='collage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='major', to='share.collagemodel', verbose_name='Collage'),
        ),
        migrations.AlterField(
            model_name='majormodel',
            name='degree',
            field=models.CharField(choices=[('BACHELOR', 'کارشناسی'), ('MASTER', 'ارشد'), ('DOCTORATE', 'دکترا')], default='BACHELOR', max_length=9, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='majormodel',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Major name'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='useremailmodel',
            name='email',
            field=models.TextField(verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='useremailmodel',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='useremailmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usermobilemodel',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='usermobilemodel',
            name='mobile',
            field=models.CharField(max_length=11, validators=[apps.share.validators.user.PhoneValidator()], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='usermobilemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superuser'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last login'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[apps.share.validators.user.NationalCodeValidator()], verbose_name='National code'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.CharField(choices=[('Male', 'آقا'), ('Female', 'خانم')], default='Male', max_length=6, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last update'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(error_messages={'unique': 'Sorry, this username already token.'}, max_length=150, unique=True, validators=[apps.share.validators.user.UsernameValidator()], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='userphonemodel',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='userphonemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='SemesterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semester', to='share.majormodel', verbose_name='Major')),
            ],
            options={
                'verbose_name': 'semester',
                'verbose_name_plural': 'semesters',
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Course name')),
                ('details', models.TextField(verbose_name='Course details')),
                ('unit', models.CharField(max_length=1, validators=[apps.share.validators.course.CourseUnitValidator()], verbose_name='Course units')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='share.majormodel', verbose_name='Collage')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='share.semestermodel', verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
    ]
