# Generated by Django 2.2.11 on 2022-09-09 08:54

import apps.share.validators.user
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=512, verbose_name='نام دانشکده')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(error_messages={'unique': 'این نام کاربری پیش از این ثبت شده است.'}, max_length=150, unique=True, validators=[apps.share.validators.user.UsernameValidator()], verbose_name='نام کاربری')),
                ('first_name', models.CharField(max_length=128, verbose_name='نام')),
                ('last_name', models.CharField(max_length=256, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, validators=[apps.share.validators.user.NationalCodeValidator()], verbose_name='کد ملی')),
                ('birthday', models.DateField(verbose_name='تاریخ تولد')),
                ('sex', models.CharField(choices=[('Male', 'آقا'), ('Female', 'خانم')], default='Male', max_length=4, verbose_name='جنسیت')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='کاربرارشد')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=11, validators=[apps.share.validators.user.PhoneValidator()], verbose_name='تلفن ثالت')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='share.UserModel', verbose_name='کاربر')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMobileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=11, validators=[apps.share.validators.user.PhoneValidator()], verbose_name='تلفن همراه')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='share.UserModel', verbose_name='کاربر')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserEmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.TextField(verbose_name='پست الکترونیکی')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='share.UserModel', verbose_name='کاربر')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(verbose_name='آدرس')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='share.UserModel', verbose_name='کاربر')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MajorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('degree', models.CharField(choices=[('BACHELOR', 'کارشناسی'), ('MASTER', 'ارشد'), ('DOCTORATE', 'دکترا')], default='BACHELOR', max_length=9)),
                ('name', models.CharField(max_length=512, verbose_name='نام رشته')),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='major', to='share.CollageModel', verbose_name='دانشکده')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
