# Generated by Django 3.2.15 on 2022-09-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='master.mastermodel', verbose_name='master'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='share.semestermodel', verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='coursedocumentmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='share.coursemodel', verbose_name='course'),
        ),
    ]
