# Generated by Django 3.2.15 on 2022-09-16 16:39

import apps.share.validators.course
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='unit',
            field=models.CharField(max_length=1, validators=[apps.share.validators.course.CourseUnitValidator()], verbose_name='Course unit'),
        ),
    ]
