# Generated by Django 3.2.15 on 2022-09-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20220916_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermobilemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userphonemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.DeleteModel(
            name='UserAddressModel',
        ),
        migrations.DeleteModel(
            name='UserEmailModel',
        ),
        migrations.DeleteModel(
            name='UserMobileModel',
        ),
        migrations.DeleteModel(
            name='UserPhoneModel',
        ),
    ]
