# Generated by Django 3.2.15 on 2022-09-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20220916_0824'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='semestermodel',
            name='name',
            field=models.CharField(default=1, max_length=512, verbose_name='Major name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='share.majormodel', verbose_name='major'),
        ),
        migrations.AlterField(
            model_name='majormodel',
            name='degree',
            field=models.CharField(choices=[('BACHELOR', 'BACHELOR'), ('MASTER', 'MASTER'), ('DOCTORATE', 'DOCTORATE')], default='BACHELOR', max_length=9, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6, verbose_name='Sex'),
        ),
    ]
