# Generated by Django 3.2.15 on 2022-10-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_useraddressmodel_useremailmodel_usermobilemodel_userphonemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='course price'),
        ),
        migrations.AlterField(
            model_name='useremailmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
