# Generated by Django 3.2.15 on 2022-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsemestercoursemodel',
            name='final_exam_grade',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='final exam grade'),
        ),
        migrations.AlterField(
            model_name='studentsemestercoursemodel',
            name='midterm_exam_grade',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='midterm exam grade'),
        ),
    ]
